version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: gemma3n-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama/models
      - ./config:/etc/ollama:ro
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=5m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gemma-network

volumes:
  ollama-models:
    driver: local

networks:
  gemma-network:
    driver: bridge